spring:
  application:
    name: userInputs
    version: '0.0.1'
    description: user Input service
  datasource:
    url: jdbc:mysql://localhost:3306/sample
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    show-sql: false

jasypt:
  encryptor:
    password: password

userInputs:
  authToken: ENC(rzHhPB85cUQU0xiF7ewearGH8rxblBpnqfZ38D2B6L0KrWGi/+z2hcpedxDWO6iL)

logging:
  level:
    root: INFO

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /api-spec.html
    operationsSorter: method

management:
  endpoints:
    web:
      exposure:
        include: metrics,info,health
  endpoint:
    metrics:
      enabled: true

